name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/assets
          
      - name: Create Web Assets and Generate Icons
        run: |
          mkdir -p www
          cp index.html www/
          # مبادرة المشروع
          npx cap init "QuranApp" "com.quran.offline" --web-dir www
          npx cap add android
          
          # توليد الأيقونات وصور التشغيل (Splash Screen) تلقائياً من ملف icon.png
          # هذه الخطوة ستقوم بإنشاء كافة المقاسات داخل مجلد أندرويد
          npx capacitor-assets generate --android

      - name: Build Android
        run: |
          npx cap copy
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Quran-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
